// Maps a product colour name to a Tailwind swatch class.
// Hoisted to module scope so it is NOT reallocated on every render — shared by
// ProductCard and ProductDetail (previously duplicated inline in both).
export const colorSwatch = {
  'Jet Black': 'bg-black border-neutral-300',
  'Pure White': 'bg-white border-neutral-300',
  'Slate Blue': 'bg-slate-600 border-transparent',
  Oatmeal: 'bg-amber-100 border-neutral-300',
  'Washed Olive': 'bg-emerald-800 border-transparent',
  'Vintage Black': 'bg-neutral-800 border-transparent',
  'Charcoal Gray': 'bg-neutral-600 border-transparent',
  'Royal Blue': 'bg-blue-700 border-transparent',
  'Sage Green': 'bg-emerald-300 border-transparent',
  'Heather Gray': 'bg-neutral-400 border-transparent',
  'Navy Blue': 'bg-blue-900 border-transparent',
  'Carbon Black': 'bg-neutral-900 border-transparent',
  'Dusty Rose': 'bg-rose-300 border-transparent',
  'Bone White': 'bg-stone-100 border-neutral-300',
  'Plum Red': 'bg-red-800 border-transparent',
  'Cobalt Blue': 'bg-blue-800 border-transparent',
  'Off White': 'bg-stone-50 border-neutral-300',
  'Deep Charcoal': 'bg-neutral-700 border-transparent',
  'Khaki Sand': 'bg-yellow-100 border-neutral-300',
  'Military Olive': 'bg-green-800 border-transparent',
  'Steel Gray': 'bg-slate-500 border-transparent',
  'Oatmeal Speckle': 'bg-amber-50 border-neutral-300',
  'Midnight Black': 'bg-black border-neutral-300',
  'Washed Sage': 'bg-green-300 border-transparent',
  'Charcoal Black': 'bg-neutral-900 border-transparent',
  'Volt Green': 'bg-lime-400 border-transparent',
  'Cream Beige': 'bg-stone-200 border-transparent',
  'Olive Gray': 'bg-stone-600 border-transparent',
  'Triple Black': 'bg-black border-transparent',
  'Neon Crimson': 'bg-red-600 border-transparent',
  'White Platinum': 'bg-stone-50 border-neutral-300',
  'Stealth Black': 'bg-neutral-950 border-transparent',
  'Pastel Pink': 'bg-pink-200 border-transparent',
  'White Silver': 'bg-stone-100 border-neutral-300',
  'Slate Dark': 'bg-slate-800 border-transparent',
  'Black Out': 'bg-black border-transparent',
  'Forest Green': 'bg-green-900 border-transparent',
  'Classic White': 'bg-white border-neutral-300',
}

export const swatchClass = (name) => colorSwatch[name] || 'bg-neutral-300 border-transparent'
