// App icon set — re-exported from lucide-react for a consistent, professional look.
// Names are aliased so every existing import keeps working unchanged.
export {
  ShoppingCart as Cart,
  Search,
  Menu,
  X as Close,
  User,
  Plus,
  Minus,
  Trash2 as Trash,
  ArrowRight,
  ArrowLeft,
  Check,
  Truck,
  ShieldCheck as Shield,
  RefreshCw as Refresh,
  Headset,
  ShoppingBag as Bag,
  Headphones,
  Shirt,
  Sofa,
  Sparkles,
  Dumbbell,
  Book,
  Eye,
  EyeOff,
  Mail,
  Lock,
  Wind,
  Footprints,
  Watch,
  Layers,
  ChevronDown,
  ChevronUp,
  ChevronRight,
  Download,
  Monitor,
  Smartphone,
  Share,
  ExternalLink,
  Sparkle,
  AlertTriangle,
  LayoutDashboard,
  Package,
  PackagePlus,
  Tags,
  Receipt,
  Users,
  LogOut,
  Upload,
  ImagePlus,
  Image as ImageIcon,
  Pencil,
  Settings,
  TrendingUp,
  DollarSign,
  Boxes,
  Filter,
  Save,
} from 'lucide-react'

import { Heart as HeartIcon, Star as StarIcon } from 'lucide-react'

// Heart and Star take a `filled` prop (wishlist state + star ratings).
export const Heart = ({ filled, ...props }) => <HeartIcon {...props} fill={filled ? 'currentColor' : 'none'} />
export const Star = ({ filled, ...props }) => <StarIcon {...props} fill={filled ? 'currentColor' : 'none'} />
